version: '4'

services:
  db:
    image: postgres:16.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: hoteldb
    volumes:
      - ./postgres:/var/lis/postgresql/data
